 File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/django/utils/cache.py", line 391, in get_cache_key
    headerlist = cache.get(cache_key)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/django/core/cache/backends/memcached.py", line 75, in get
    return self._cache.get(key, default)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/pymemcache/client/hash.py", line 347, in get
    return self._run_cmd("get", key, default, default=default, **kwargs)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/pymemcache/client/hash.py", line 322, in _run_cmd
    return self._safely_run_func(client, func, default_val, *args, **kwargs)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/pymemcache/client/hash.py", line 199, in _safely_run_func
    result = func(*args, **kwargs)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/pymemcache/client/base.py", line 687, in get
    return self._fetch_cmd(b"get", [key], False, key_prefix=self.key_prefix).get(
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/pymemcache/client/base.py", line 1133, in _fetch_cmd
    self._connect()
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/pymemcache/client/base.py", line 389, in _connect
    info = s.getaddrinfo(host, port, s.AF_UNSPEC, s.SOCK_STREAM, s.IPPROTO_TCP)
  File "/nix/store/lwl8ysfi2hhcyki6pc9qqbybzm5z55wv-python3-3.9.21/lib/python3.9/socket.py", line 966, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Could not fetch page from cache backend.
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/wagtailcache/cache.py", line 219, in process_request
    cache_key = _get_cache_key(request, self._wagcache)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/wagtailcache/cache.py", line 163, in _get_cache_key
    return get_cache_key(r, None, r.method, c)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/django/utils/cache.py", line 391, in get_cache_key
    headerlist = cache.get(cache_key)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/django/core/cache/backends/memcached.py", line 75, in get
    return self._cache.get(key, default)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/pymemcache/client/hash.py", line 347, in get
    return self._run_cmd("get", key, default, default=default, **kwargs)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/pymemcache/client/hash.py", line 322, in _run_cmd
    return self._safely_run_func(client, func, default_val, *args, **kwargs)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/pymemcache/client/hash.py", line 199, in _safely_run_func
    result = func(*args, **kwargs)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/pymemcache/client/base.py", line 687, in get
    return self._fetch_cmd(b"get", [key], False, key_prefix=self.key_prefix).get(
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/pymemcache/client/base.py", line 1133, in _fetch_cmd
    self._connect()
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/pymemcache/client/base.py", line 389, in _connect
    info = s.getaddrinfo(host, port, s.AF_UNSPEC, s.SOCK_STREAM, s.IPPROTO_TCP)
  File "/nix/store/lwl8ysfi2hhcyki6pc9qqbybzm5z55wv-python3-3.9.21/lib/python3.9/socket.py", line 966, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known